export {default as BorderedRectangle} from './bordered-rectangle'
export {default as Borders} from './borders'
export {default as Rectangle, Rectangular } from './rectangle'
export {default as Scale} from './scale'
export {default as Point} from './point'
export {default as Size} from './size'
