name: Publish

on:
  release:
    types: [published]

jobs:

  publish-github-package-registry:
    name: Publish new version to GitHub Package Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install -g yarn
      - run: npm config set //npm.pkg.github.com/:_authToken  ${{ secrets.ADQUE_NPM_TOKEN }}
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
